# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 18:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmid', models.IntegerField()),
                ('farmowner', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('plot', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('members', models.IntegerField()),
                ('income', models.FloatField()),
                ('pointer', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellid', models.IntegerField()),
                ('depth', models.FloatField()),
                ('owner', models.CharField(max_length=50)),
                ('avg_yield', models.FloatField()),
                ('pointer', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
