# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 23:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.IntegerField()),
                ('farm_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('farm_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='members',
            new_name='household_id',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='pointer',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='avg_yield',
            new_name='average_yield',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='wellid',
            new_name='farm_associated',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='pointer',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.AddField(
            model_name='household',
            name='no_of_members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='well_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='income',
            field=models.IntegerField(),
        ),
    ]
